version: '3.8'

services:
  slash-z:
    build: .
    container_name: slash-z
    environment:
      - NODE_OPTIONS=--max-old-space-size=492  # ~0.5GB
    env_file:
      - .env
    ports:
      - "3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

